### ISSUE TITLE
Re-entering XR on Android causes a debug assert

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#105]
In the Android Playground app, if you enter XR mode, then exist, then enter again, there is a debug assert in BGFX. If the debugger is not attached, then this crashes the app (for debug builds). You also briefly see the last frame from the previous XR session, so it seems like some state is not getting cleaned up.

**Comment by bghgary** [comment]
Doesn't repro anymore. Not sure what changed :)
