### ISSUE TITLE
iOS display issues

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonReactNative#109]
2 display issues
repro steps:
- Hide engine view->rotate screen-> show engine view => no 3D display but a toggle view off/o and the display is back
- start XR - >toggle engine view 2 times-> no 3D display. Stop XR brings back the 3D view display

**Comment by ryantrem** [comment]
These issues no longer repro. Presumably fixed by changes we've made since this issue was opened.
