### ISSUE TITLE
Dev mode reload crashes if a glb has been loaded

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#123]
We fixed a bunch of things to support dev mode reload (press 'R' in the Metro Server console window, or shake a device and tap the "Reload" button). However, there is still a crash that happens if a glb has been loaded. Since the Babylon React Native Playground app now loads a glb, this is very easy to repro.

**Comment by CedricGuillemet** [comment]
I'm taking a look.

**Comment by ryantrem** [comment]
@CedricGuillemet mentioned in side conversation he couldn't repro this. I just retested with the latest bits on both Android and iOS and it didn't repro on either for me. Presumably some other change (@CedricGuillemet's BGFX update maybe?) fixed this.
