### ISSUE TITLE
Get reset (e.g. bgfx::shutdown) working with fast refresh

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#125]
As mentioned here: https://github.com/BabylonJS/BabylonNative/issues/523#issuecomment-736574732

Fast refresh is not working with the bgfx::shutdown call that happens while tearing down an engine in `useEngine`. As a quick fix, I am disabling the bgfx::shutdown call for dev mode builds (e.g. only release graphics resources in release builds). This isn't great, but it's proving rather difficult to fix due to details of how fast refresh works. We should try to fix this so both debug and release builds behave the same.

**Comment by CedricGuillemet** [comment]
Assigning myself this issue as it's appearing with one partner.

**Comment by CedricGuillemet** [comment]
ReactNative has a cache mecanism for fast refresh.
For example, on Android, the surfaceview is not destroyed and recreated when a fast refresh occurs. BabylonNative handles the bgfx context initialization when the surfaceView changed. But as it's kept alive: bgfx shutdown happens but no context initialization. And a crash happens at trying to create resources (texture, vertex buffer,...)

There is a work around: Adding `// @refresh reset` before the `return` in App.tsx will force the display to be re-evaluated.
It's more a confirmation than really a workaround actually. Some infos here : https://reactnative.dev/docs/fast-refresh

I suspect this is the same issue encounterd with a partner. I guess the surfaceView is not destroyed/recreated and re-init doesn't happen.

**Comment by CedricGuillemet** [comment]
I'm doing more tests with  `// @refresh reset` to validate everything works fine when view is reset and I get a crash in TextureLoad. I'm wondering if it's related to https://github.com/BabylonJS/BabylonNative/issues/634
