### ISSUE TITLE
Issue with app cleanup of babylon after screen is switched.

### ISSUE THREAD

**Issue by seand88** [BabylonJS/BabylonReactNative#130]
We are using the code below.
After we switch away to a different screen it continues to try to draw to a gl surface, but obviously one isnt found.
This is on android and logcat keeps showing these errors.

We are using react tab UI, wondering how we can tell babylon to stop drawing when we switch tabs. 
The tabs are cached so I think it keeps trying to draw even after tab is switched.

```
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
E/EGL_emulation: tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
    tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
    tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
    tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
    tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
    tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
E/EGL_emulation: egl_window_surface_t::swapBuffers called with NULL buffer
    tid 6483: swapBuffers(639): error 0x300d (EGL_BAD_SURFACE)
```

```
import React, {useEffect, useState} from 'react';

import {EngineView, useEngine} from '@babylonjs/react-native';
import {
    ArcRotateCamera,
    Camera,
    Color4,
    DeviceSource,
    DeviceSourceManager,
    DeviceType,
    HemisphericLight,
    PointerInput,
    Scene,
    SceneLoader,
    TransformNode,
    Vector3
} from '@babylonjs/core';
import '@babylonjs/loaders';
import {StyleProp, StyleSheet, ViewStyle} from "react-native";

type Props = {
    style?:  StyleProp<ViewStyle>
}

const CharacterDisplay = (props: Props) => {
    const engine = useEngine();
    const [camera, setCamera] = useState<Camera>();

    const [rootNode, setRootNode] = useState<TransformNode>();


    useEffect(() => {
        if (engine) {
            const scene = new Scene(engine);

            const camera = new ArcRotateCamera("Camera", 0, 0, 10, new Vector3(0, 1, .2), scene);
            camera.setPosition(new Vector3(1, 2, 3));
            camera.lowerRadiusLimit = 2.3;
            camera.upperRadiusLimit = 3;

            setCamera(scene.activeCamera!);
            scene.createDefaultLight(true);
            scene.clearColor = new Color4(0, 0, 0, 0);
            const light = new HemisphericLight('light1', new Vector3(0, 1, 0), scene);

            const rootNode = new TransformNode("Root Container", scene);
            setRootNode(rootNode);

            const deviceSourceManager = new DeviceSourceManager(engine);
            deviceSourceManager.onDeviceConnectedObservable.add(device => {
                if (device.deviceType === DeviceType.Touch) {
                    const touch: DeviceSource<DeviceType.Touch> = deviceSourceManager.getDeviceSource(device.deviceType, device.deviceSlot)!;
                    touch.onInputChangedObservable.add(touchEvent => {
                        if (touchEvent.inputIndex === PointerInput.Horizontal) {
                            if (touchEvent.currentState && touchEvent.previousState) {
                                rootNode.rotate(Vector3.Down(), (touchEvent.currentState - touchEvent.previousState) * 0.005);
                            }
                        }
                    })
                }
            })

            SceneLoader.ImportMeshAsync("", "https://files.dragonsofthevoid.com/character/base_char/char.gltf").then(result => {
                const mesh = result.meshes[0];
                mesh.parent = rootNode
            });
            SceneLoader.ImportMeshAsync("", "https://files.dragonsofthevoid.com/character/equipment/weapons/swords/starter_sword.gltf").then(result => {
                const mesh = result.meshes[0];
                mesh.parent = rootNode
            });
            SceneLoader.ImportMeshAsync("", "https://files.dragonsofthevoid.com/character/equipment/shields/pentwaters-stand.gltf").then(result => {
                const mesh = result.meshes[0];
                mesh.parent = rootNode
            });
        }
    }, [engine]);

    return (
        <EngineView style={[styles.engineView, props.style]} camera={camera}/>
    );
};

export default CharacterDisplay;


const styles = StyleSheet.create({
    engineView: {
        backgroundColor: 'transparent'
    }
});
```

**Comment by ryantrem** [comment]
Hey @seand88, thanks for the feedback. The render loop is managed automatically in `EngineView`:

https://github.com/BabylonJS/BabylonReactNative/blob/8627740e492a43b75e858754716d3e9cb7662087/Modules/%40babylonjs/react-native/EngineView.tsx#L65-L85

Effectively the render loop is stopped when `EngineView` is unmounted. In your scenarios, it sounds like `EngineView` is staying mounted in the React JSX tree, but the underlying native view is being deactivated in some way, which sounds like a bug (e.g. we made some assumption that isn't always true). I think we'd need to see the code that consumes `CharacterDisplay` to have any other ideas of what is going on. What would help the most though is if you could either:

1. Provide a repro project (getting an answer might be slower).
1. Do a little more guided debugging (getting an answer might be faster).

If you want to try to dig in yourself some more, I would start by either attaching a debugger (to the JS) or adding some `console.log` statements to try to understand whether `EngineView` is being unmounted or not.

Also, if you want to try a workaround, you can also cause the render loop to stop by setting the `camera` prop to `null` on your `EngineView`. If you can do that when the tab is changing, it might be a short term solution to your problem. My sense at this point though is that Babylon React Native itself should be robust to your scenario.

**Comment by seand88** [comment]
@ryantrem appreciate the quick response! we have someone who has more experience with mobile joining the project in the next week or two, so I will keep you updated as we diagnose this.

**Comment by bghgary** [comment]
@seand88 Hey, do you have an update on this? Thanks.

**Comment by seand88** [comment]
Hey @bghgary the person who had more mobile experience didn't end up joining the project so unfortunately haven't solved this yet. Were still able to make progress on our project so hasn't caused any major issues yet I'm aware of.

**Comment by seand88** [comment]
We can put a sample project together to repro the issue if that helps.

**Comment by bghgary** [comment]
@seand88 Any news?

**Comment by seand88** [comment]
no, we are in crunch mode releasing open beta for our game's web version using babylonjs web.
After that we are getting back into mobile, so its gonna be a couple weeks to get a example repo created.

Here is the forum post if you want to check it out. https://forum.babylonjs.com/t/web-rpg-dragons-of-the-void/9589

**Comment by bghgary** [comment]
Closing for now. Please reopen if you can get a repro. Thanks!
