### ISSUE TITLE
this._native.clearColor is not a function

### ISSUE THREAD

**Issue by swese44** [BabylonJS/BabylonReactNative#148]
I'm having trouble getting a simple demo to render. I'm new to Babylonjs so I'm not sure if I'm making an obvious mistake or if there's a bug. I'm using @babylonjs/core: 4.2.0 and @babylonjs/react-native: 0.4.0-alpha.6.

I'm trying to render the playground demo:

```ts
import { useEngine, EngineView } from "@babylonjs/react-native"
import { Scene, Camera, MeshBuilder, FreeCamera, Vector3, HemisphericLight } from "@babylonjs/core"
import React, { FC, useEffect, useState } from "react"

const engineStyle = { flex: 1, backgroundColor: "red" }

export const BabylonTest: FC = () => {
  const engine = useEngine()
  const [camera, setCamera] = useState<Camera>()

  const createScene = function () {
    // This creates a basic Babylon Scene object (non-mesh)
    const scene = new Scene(engine)

    // This creates and positions a free camera (non-mesh)
    const camera = new FreeCamera("camera1", new Vector3(0, 5, -10), scene)
    setCamera(camera)

    // This targets the camera to scene origin
    camera.setTarget(Vector3.Zero())

    // This attaches the camera to the canvas
    // camera.attachControl(canvas, true);

    // This creates a light, aiming 0,1,0 - to the sky (non-mesh)
    const light = new HemisphericLight("light", new Vector3(0, 1, 0), scene)

    // Default intensity is 1. Let's dim the light a small amount
    light.intensity = 0.7

    // Our built-in 'sphere' shape.
    const sphere = MeshBuilder.CreateSphere("sphere", { diameter: 2, segments: 32 }, scene)

    // Move the sphere upward 1/2 its height
    sphere.position.y = 1

    // Our built-in 'ground' shape.
    const ground = MeshBuilder.CreateGround("ground", { width: 6, height: 6 }, scene)

    return scene
  }

  useEffect(() => {
    if (engine) {
      const scene = createScene()
    }
  }, [engine])

  return <EngineView style={engineStyle} camera={camera} />
}

```

<img width="384" alt="Screen Shot 2021-01-31 at 10 11 53 PM" src="https://user-images.githubusercontent.com/471731/106421387-754af380-6411-11eb-8360-f34693826acb.png">

**Comment by ryantrem** [comment]
With that version of Babylon React Native you need at least version 5.0.0-alpha.6 of Babylon.js. You should have gotten an npm warning when you did npm install about this. I also have a PR open that does a runtime check on the Babylon.js version and produces a more obvious error which would probably help. Will you please verify it works as expected if you update the version of Babylon.js though?

**Comment by swese44** [comment]
Up and running now, thank you!

<img width="368" alt="Screen Shot 2021-02-01 at 8 45 04 AM" src="https://user-images.githubusercontent.com/471731/106489642-d8687480-6469-11eb-8e29-6455a9fefd36.png">
