### ISSUE TITLE
Playground crashes on android due to debug assert in xr lifecycle scenario

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonReactNative#150]
Repro:

1. Launch Playground app on android
2. Enter xr mode
3. Exit xr mode
4. Hide EngineView
5. Show EngineView

Observed:
Application crashes for debug builds due to assert

Expected:
Application doesn't crash

**Comment by bghgary** [comment]
Check with  frame buffer PR.

**Comment by bghgary** [comment]
Works fine now.

**Comment by bghgary** [comment]
#591
