### ISSUE TITLE
enterXRAsync override in EngineHook.ts fails TypeScript type checking

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#170]
EngineHook.ts has an override of `WebXRExperienceHelper.enterXRAsync` to force the clear color. To do this, it accesses the `scene` property of `WebXRExperienceHelper`, but this is private (I'm guessing it used to be public). This results in a TypeScript type checking error. We should:

1. Ideally just remove this if @bghgary's big refactor fixes it (I'm guessing it does).
1. If we must keep it, we should change `this.scene` to `this.sessionManager.scene`.

**Comment by chrisfromwork** [comment]
Testing this out locally, it seems like @bghgary 's changes didn't change things to the point that we can remove this auto clear logic. I'll put out a change updating the line for typescript type checking
