### ISSUE TITLE
Getting undefined in useEngine() hook.

### ISSUE THREAD

**Issue by anmoldh121** [BabylonJS/BabylonReactNative#182]
In, `const engine = useEngine()`
i am getting engine as undefined, also getting warning
`TypeError: null is not an object (evaluating 'BabylonModule.initialize')
ensureInitialized$`

**Comment by ryantrem** [comment]
Is this in your own react native project, or in the Babylon React Native Playground test app? Which source branch or npm package version are you trying?

**Comment by anmoldh121** [comment]
I am using it in my own project. The version i am using is, 
`
"@babylonjs/react-native": "^0.4.0-alpha.13",
"@babylonjs/core": "^5.0.0-alpha.15",
`

**Comment by anmoldh121** [comment]
Looks like its react-native problem, after some debugging i found that NativeModule Object is empty in my case. It is this [issue](https://github.com/facebook/react-native/issues/26813)

**Comment by bghgary** [comment]
It sounds like you got this working. Please reopen if you still have issues.
