### ISSUE TITLE
UWP: BabylonReactNative.dll compilation targets don't wait for BuildBabylonNativeStaticLibs completion

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonReactNative#198]
We should fix this so that all BabylonReactNative dependencies are rebuilt when building the BabylonReactNative.dll

**Comment by CedricGuillemet** [comment]
This will be the case, by design, with React Native Test App: https://github.com/BabylonJS/BabylonReactNative/pull/641
Closing.
