### ISSUE TITLE
Need a story for locally testing npm pack

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonReactNative#202]
(#200) introduced a change to the `@babylon/react-native` and `@babylon/react-native-windows` npm modules. Every change to the modules also changes their checksums (see 7ca1e794b64e31b45b43ae0824892f2e3a668b61), and without revving the version number, `npm install` will fail in the [PackageTest apps](https://github.com/BabylonJS/BabylonReactNative/tree/master/Apps/PackageTest), because the [checksum stored in the package-lock.json](https://github.com/BabylonJS/BabylonReactNative/blob/master/Apps/PackageTest/0.64.0/package-lock.json#L1211) doesn't match for "version 0.0.1". This is to be expected, and will occur for any changes made to our npm packages.

I'm open to other suggestions, but I think the best way to fix this would be:
Delete + gitignore the package-lock.json files in the PackageTest apps, and write documentation that says to install modules in the PackageTest app with `npm install --no-package-lock`.

**Comment by ryantrem** [comment]
I’ve always just done an npm uninstall @babylonjs/react-native and then reinstall with the locally built package path, though I don’t think this is documented. Will this work for you?

**Comment by ryantrem** [comment]
We could automate this with another gulp command for the package as well.
