### ISSUE TITLE
Can't build app on android

### ISSUE THREAD

**Issue by dmegue** [BabylonJS/BabylonReactNative#212]
I'm having issues trying to build the app on android, i have just added the package to a fresh RN project.

Thats the error i'm getting:

> Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade     
   > More than one file was found with OS independent path 'lib/arm64-v8a/libturbomodulejsijni.so'

Could someone point me out what could be causing this issue? Thanks.

**Comment by dmegue** [comment]
Adding packaging options to android/app/build.gradle fixed the issue. Closing this out.

` packagingOptions {
    pickFirst '**/libturbomodulejsijni.so'
}`

**Comment by ryantrem** [comment]
This is an issue with using Babylon React Native with React Native >= 0.64. The following issue is tracking this: https://github.com/BabylonJS/BabylonReactNative/issues/192
