### ISSUE TITLE
Pointer position for raycast

### ISSUE THREAD

**Issue by Papakkkarlo** [BabylonJS/BabylonReactNative#214]
Hello, i need a raycast in my app to pick the meshes the problem is that `onInputChangedObservable` returns the event information in such way that is not very conviniend to trace actual touch position on every touch input.  At the same time `scene.pointerX` and `scene.pointerY` are always zero.

Is there any way to get `pointerX` and `pointerY` onPointerDown or what can be a possible workaround?

**Comment by star-collector** [comment]
I didn't find any out-of-the-box solution as well, so I had to use native View's `onTouchStart` event for similar purposes.

**Comment by ryantrem** [comment]
Can you explain more what you mean by this:
> Hello, i need a raycast in my app to pick the meshes the problem is that onInputChangedObservable returns the event information in such way that is not very conviniend to trace actual touch position on every touch input. 

You should be able to do this (might be typos in this code):
```ts
const deviceSourceManager = new DeviceSourceManager(engine);
const afterDeviceConnectedObserver = deviceSourceManager.onDeviceConnectedObservable.add(deviceEventData => {
  if (deviceEventData !== undefined && deviceEventData.deviceType === DeviceType.Touch) {
    const touchDeviceSource: DeviceSource<DeviceType.Touch> = deviceSourceManager.getDeviceSource(deviceEventData.deviceType, deviceEventData.deviceSlot)!;
    touchDeviceSource.onInputChangedObservable.add(inputEventData => {
      const x = touchDeviceSource.getInput(PointerInput.Horizontal);
      const y = touchDeviceSource.getInput(PointerInput.Vertical);
      scene.pick(x, y, (mesh) => {
        // do stuff with the picked mesh
      });
    });
  }
});
```

Also @polygonalsun has work underway that will make the existing higher level input system exposed by scene work on top of `DeviceSourceManager`, which might make this easier, so he might have more comments on this as well.

**Comment by Papakkkarlo** [comment]
Thank you! I did not know about `getInput` method. `x` and `y` coordinates is exactly what i needed.
