### ISSUE TITLE
Mesh highlighting

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#215]
Hi! Mesh highlighting doesn't seem to work for me. I add a highlight layer and the picture comes out almost completely black. Same behaviour on both Android and iOS. Also, there is no way to set stencil option for EngineView (maybe that's why highlighting doesn't work properly).

![photo_2021-05-06_19-11-27](https://user-images.githubusercontent.com/19988178/117330988-f4cbe100-ae9e-11eb-8cb8-462b6a7ba677.jpg)

**Comment by CedricGuillemet** [comment]
I've done the plumbing to support stencil func in BabylonNative. But I faced the same issue for the shadows: a post process pass is performed to blur the result. Because of inverted Y in render target pass, highlight is also Y inverted.

**Comment by star-collector** [comment]
@CedricGuillemet I built BabylonNative with recent stencil commit on my machine, replaced files in react-native folder with content of Assembled folder, updated @babylonjs/core package to alpha-29. App launches without a problem, there is no freezing like alpha-29 did prior file replacement. However highlight layer still doesn't seem to work. I enable stencil through engine.setStencilBuffer(true) and the picture comes out the same. Am I doing something wrong or there are more work to be done on your side in order for highlight layer to work?

**Comment by ryantrem** [comment]
@rarattay you got mesh highlighting working recently right? Any insights here?

**Comment by rarattay** [comment]
I was able to get mesh highlighting via a HighlightLayer to work in the Babylon Native and Babylon React Native playgrounds once @CedricGuillemet 's initial stencil buffer support PR went in (https://github.com/BabylonJS/BabylonNative/commit/30a574bf1f337444388c87fa9d5bd7f4542f9517). 

To get this working all I did was pull latest master of this repo (Babylon React Native) and then updated the BabylonNative submodule to latest master (inclusive of the commit linked above). Then to test out adding a highlight layer I added this right after the default model is imported in playground's App.tsx:

result.meshes.forEach(mesh => {
        var hl = new HighlightLayer("hl1", scene);
        hl.addMesh(mesh as Mesh, Color3.White());  
});

**Comment by ryantrem** [comment]
I believe @chrisfromwork will be updating BabylonReactNative to the latest BabylonNative and publishing a new NPM package in the next few days.

**Comment by CedricGuillemet** [comment]
I'm still debugging highlighting + XR. There a 1 frame lag. I hope to get it fixed in the coming days.

**Comment by star-collector** [comment]
@ryantrem I checked new package version (0.4.0-alpha.23) and got the same results - everything is pitch black except highlighted meshes which are completely covered in highlight color overlay-style. Then I tried testing highlight layer using App.tsx code from your Playground app and everything again renders pitch black after enabling highlight layer and adding mesh to it.

**Comment by CedricGuillemet** [comment]
Tested ok with AR thanks to this PR : https://github.com/BabylonJS/BabylonNative/pull/819

**Comment by ryantrem** [comment]
@star-collector will you commit your test code in a branch, push to your fork, and share a link so we can investigate a repro?

**Comment by star-collector** [comment]
> @star-collector will you commit your test code in a branch, push to your fork, and share a link so we can investigate a repro?

Yes, I can. But first, can you tell me if I enable stencil the right way for BabylonReactNative?

`engine.setStencilBuffer(true);`

I do this right before I add HighlightLayer. Is this correct?

**Comment by CedricGuillemet** [comment]
You don't have to change anything with the stencil to get a highlighting layer.
Basically., you just need to create one and add mesh to it:
```
var box = BABYLON.Mesh.CreateBox("box1", 0.2);
var hl = new BABYLON.HighlightLayer("hl1", scene);
hl.addMesh(box, BABYLON.Color3.Green());
```

**Comment by star-collector** [comment]
@CedricGuillemet @ryantrem 

Ok, I tested again and it seems like the problem persist only on iOS. For some reason, I didn't test HighlightLayer layer on Android before. It works on this platform: 

![photo_2021-07-07_17-27-32](https://user-images.githubusercontent.com/19988178/124778012-4ea56180-df49-11eb-8174-c614528692ac.jpg)

However, I still get this on iOS:

![photo_2021-07-07_17-33-37](https://user-images.githubusercontent.com/19988178/124778296-8ad8c200-df49-11eb-97ee-77ea2744e082.jpg)

And for some reason I still get warning about stencil in console:

<img width="559" alt="Screenshot 2021-07-07 at 17 18 07" src="https://user-images.githubusercontent.com/19988178/124778371-9d52fb80-df49-11eb-8b14-13ce01051501.png">

I'll provide sample app if needed.

**Comment by CedricGuillemet** [comment]
I can repro on iOS with latest master. I'm investigating.

**Comment by CedricGuillemet** [comment]
I've found a workaround. It looks like MSAA + stencil do not work on iOS device (works on simulator and on MacOS, so might not be a Metal issue. Maybe a driver one).
To disable MSAA for Metal, remove `BGFX_RESET_MSAA_X4` on this line : 
https://github.com/BabylonJS/BabylonNative/blob/954a6007b1b5ef6c4f45297e44e486fbad7dd177/Core/Graphics/Source/Apple/Babylon/GraphicsPlatformImpl.h#L7

I need more time to do a smaller repro and figure out the real problem.

**Comment by ryantrem** [comment]
Should we just disable MSAA on iOS for now, especially since it is disabled on Android? What is the tangible visual impact? How does it affect perf?

**Comment by star-collector** [comment]
I noticed another highlighting bug. If a highlighted object is only partially inside a camera, then opposite side of the camera starts glowing as well.

![photo_2021-08-03_12-55-57](https://user-images.githubusercontent.com/19988178/127997176-43c0f9c8-b72f-4715-87be-a79a8c89ece2.jpg)

Here this bug is visible on both shelf and TV. Left side is glowing, however there is no actual object to glow.

**Comment by CedricGuillemet** [comment]
I was able to find a repro and it seems related to our rendering lib.  An issue has been open:

https://github.com/bkaradzic/bgfx/issues/2620

I continue the investigations.

**Comment by bghgary** [comment]
Should we disable MSAA on iOS to work around this for now?

**Comment by CedricGuillemet** [comment]
> Should we disable MSAA on iOS to work around this for now? MSAA is already disabled on Android.

Enabling MSAA on Android will crash whereas MSAA on iOS will "only" make highlighting rendering glitched. I don't know if it's better to disable it or only warn/alert when user face the problem. And user will disable MSAA themselves. It doesn't seem like many users are using HL on iOS for now.

**Comment by CedricGuillemet** [comment]
Closing this issue. https://github.com/BabylonJS/BabylonNative/issues/988 has been open for centralizing issues with MSAA.
