### ISSUE TITLE
BabylonReactNative should support keyboard input

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonReactNative#216]
Right now BabylonNative.h doesn't expose anything to submit key presses to the js engine.

**Comment by chrisfromwork** [comment]
Note this work requires the following: https://github.com/BabylonJS/BabylonNative/issues/737

**Comment by runtothedoor** [comment]
> Right now BabylonNative.h doesn't expose anything to submit key presses to the js engine.

I know this feature is still missing but I'm currently working on a library ([rxn-keylistener](rxn-keylistener)) that intends to use the same API for React or React Native to handle keyboard input, it's not even half ready yet but if you're interested in a slightly more stable library for React Native I recommend [react-native-keyevent](https://github.com/kevinejohn/react-native-keyevent).

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.

Related: https://github.com/BabylonJS/BabylonNative/issues/1143
