### ISSUE TITLE
FPS drops significantly until camera prop set to undefined and back to active camera again

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#220]
Found another bug. My application has a character model inside a 3D room. Character also has animations which play in a continuous loop.  This scene lags a lot and FPS counter shows 20-25 FPS. However, if I temporary set camera prop for EngineView to `undefined` and then return it back  to my active camera after one React render iteration - lagging stops, FPS jumps to almost 40 and stays this way until I restart my app.

**Comment by ryantrem** [comment]
Is this on iOS or Android or both? Will you share some code so we can try to reproduce this behavior?

**Comment by star-collector** [comment]
> Is this on iOS or Android or both? Will you share some code so we can try to reproduce this behavior?

Both. However, I made a double check and the problem seems to be in my code. I call unneeded `scene.render()` by mistake which leads to FPS drops and for some reason EngineView's camera prop toggle removes this second render on engine's side. I'll close the issue since this isn't a problem of react-babylon-native.
