### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#229]
There seems to be a memory leak connected to model loading. I load my character model, then load another two models as asset containers:

`
const character = await SceneLoader.ImportMeshAsync('', characterPath);
`
`
const baseContainer = await SceneLoader.LoadAssetContainerAsync(baseModelPath);
`
`
const walkContainer = await SceneLoader.LoadAssetContainerAsync(walkAnimationPath);
`

I do what I need with resources from containers and dispose them. Then I move to another screen in my app, so EngineView will get disposed and it's unmount cycle starts. Then I return back, so my model appears again. However, I experience crash due to lack of memory (or at least XCode says so). Same behaviour on both iOS and Android.

I made a simple app based on your Playground App and react-babylonjs to reproduce this: https://github.com/star-collector/babylon-playground
Just wait until a character appears, then press button at the bottom to unmount/mount Engine. Crash usually happens on 4th attempt.

In my original app, crash happens immediately after I try to mount EngineView second time, possibly because my app conducts character creation requests to my server and does react-navigation stack animations which also consume some memory.

**Comment by bghgary** [comment]
We fixed [a bug in Babylon.js](https://github.com/BabylonJS/Babylon.js/issues/10433) that was causing leaks when using asset containers. I think this is likely the same issue that is causing this memory leak. Once this change is picked up (Babylon.js `5.0.0-alpha.25`), then we should recheck to see if the leak is still there.

**Comment by star-collector** [comment]
Yeah, seems like everything is fine. Thank you.
