### ISSUE TITLE
Coloring instances using instancedBuffer

### ISSUE THREAD

**Issue by Papakkkarlo** [BabylonJS/BabylonReactNative#232]
Hello! I'm trying to color mesh instances on `BabylonReactNative` scene using this example: https://playground.babylonjs.com/#YPABS1
But when i move code that works in playground to `BabylonReactNative` scene all instances keeps appearing black.
Is there any specific `BabylonReactNative` issues with `instancedBuffers` ?

**Comment by ryantrem** [comment]
@CedricGuillemet where are we at with instance support?

**Comment by CedricGuillemet** [comment]
@ryantrem I had a quick look some weeks ago. It's a 2 parts work: handle the dynamic buffer on the C++ side and add instance buffer attribute in the shader. For the later part I don't know the amount of work it needs. I guess it will need changes on nativeShaderProcessor, maybe the shader traversals.

**Comment by CedricGuillemet** [comment]
Work has been done https://github.com/BabylonJS/BabylonNative/pull/990
Reopen this issue if needed
