### ISSUE TITLE
Frame Width and Height not updated when changed in the middle of an ongoing capture session

### ISSUE THREAD

**Issue by bonnyMahajan10** [BabylonJS/BabylonReactNative#238]
Observed from ARViewTest App.
If I start a NativeCaptureSession when in Portrait mode on my phone, and switch while the session is ongoing - the variables for capturedFrame.width and capturedFrame.height remain the same as they were at the start of the session (instead of being updated). I imagine if my phone changes orientation (say portrait to landscape or vice versa) - these variable should (roughly not exactly) switch.

**Comment by andrewmo2014** [comment]
For our use case, we lock device orientation when capturing videos. By _not_ doing so, the following artifacts can be observed when capturing frames and switching orientation (portrait to landscape):

https://user-images.githubusercontent.com/2365108/139757668-5b0ca382-56f1-42ca-a3e9-ccc1af047db5.mp4

Are there any safeguards that can be introduced on the Babylon Native side, or is our workaround of locking the device orientation while capturing videos sufficient?
