### ISSUE TITLE
Problem with lighting (?) on some meshes

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#243]
I noticed there is a problem rendering some meshes (specifically shelf's underneath in my test app) when they are under lights. This is how problem part of 3D scene looks (and should look) in Babylon.js on https://sandbox.babylonjs.com

<img width="253" alt="Screenshot 2021-06-09 at 10 55 39" src="https://user-images.githubusercontent.com/19988178/121315857-69b48f80-c911-11eb-8d92-a30bb875734a.png">

And this is how it looks in my app on Android:

<img width="277" alt="Screenshot 2021-06-09 at 10 59 14" src="https://user-images.githubusercontent.com/19988178/121316224-c44deb80-c911-11eb-8bfa-fa4f46f96cc6.png">

It doesn't matter where I put lights, even if I put a light underneath the shelf this rendering problem still occurs. iOS build has similar problem, except shelf's underneath actually renders but has weird grainy effect.

Here is my sample app where you can reproduce the problem:

https://github.com/star-collector/babylon-playground

**Comment by sebavan** [comment]
It looks like you did not set an environmentTexture on your scene in your app which is automatic in the sandbox.

You should have a look at : https://doc.babylonjs.com/divingDeeper/materials/using/HDREnvironment
