### ISSUE TITLE
App crashes with @babylonjs/react-native above alpha.24 on Android

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#264]
**Describe the bug**
it seems like something broke in alpha.25 and above. Any attempt to render 3D scene on Android leads to crash. Tested on several devices. iOS build works fine.

**To Reproduce**
1. Open app with @babylonjs/react-native alpha.25  on Android (example - https://github.com/star-collector/babylon-playground, I updated packages specifically for this issue, alpha.24 works)
2. App crashes

**Expected behavior**
App renders 3D scene without crash

**Other**
 - Platform: Android

**Comment by ryantrem** [comment]
@star-collector I've tested alpha.25+ packages with the [PackageTest](https://github.com/BabylonJS/BabylonReactNative/tree/master/Apps/PackageTest/0.63.1) app without any issues on Android (haven't tried your app). Do you see exceptions in the logcat window?

**Comment by star-collector** [comment]
> @star-collector I've tested alpha.25+ packages with the [PackageTest](https://github.com/BabylonJS/BabylonReactNative/tree/master/Apps/PackageTest/0.63.1) app without any issues on Android (haven't tried your app). Do you see exceptions in the logcat window?

Yes, I do.

<img width="1164" alt="Screenshot 2021-07-26 at 18 59 47" src="https://user-images.githubusercontent.com/19988178/127021122-ca129e50-3379-425a-bbe7-0f0f8591b54e.png">

And then some other logs later:

`WindowManager: WINDOW DIED Window{4908cce u0 com.playground/com.playground.MainActivity}`

**Comment by ryantrem** [comment]
Oh interesting, I think that must be from this change (which happened between alpha.24 and alpha.25): https://github.com/BabylonJS/BabylonReactNative/commit/b4fec8c027c91ff68ca8006b3fd4484803f90e27

But I'm not sure why this isn't happening consistently on all devices/apps. @CedricGuillemet any ideas by chance?

@star-collector to help diagnose, can you try manually adding back the line (`implementation 'com.google.ar:core:1.14.0'`) to that file (`node_modules/@babylonjs/react-native/Android/build.gradle`) for your app and see if it fixes the problem?

**Comment by star-collector** [comment]
@ryantrem Yes, it fixed the problem. My app rendered 3D without crash.

**Comment by ryantrem** [comment]
Actually I forgot that the `PackageTest` app doesn't do any XR/MR/AR, so maybe we just broke it. I will do some more testing today.

**Comment by ryantrem** [comment]
Ok I am able to repro this. I will work on a fix today.

**Comment by ryantrem** [comment]
This is fixed in 0.4.0-alpha.29, which should be available within the next hour.
