### ISSUE TITLE
Dependabot should open prs for babylonnative changes

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonReactNative#270]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Is your feature request related to a problem? Please describe.**
We should configure Dependabot to open prs for babylonnative changes

**Describe the solution you'd like**
Update Dependabot config file.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bghgary** [comment]
Closing for now. If we want it, reopen.
