### ISSUE TITLE
Packages above alpha.29 are broken

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#275]
**Describe the bug**
Packages above alpha.29 are broken. They crash when 3D scene starts rendering on Android. Alpha.29 itself does seem to work fine.

**To Reproduce**
1. Create fresh app with @babylonjs/react-native 0.4.0-alpha.31 (or use this sample app https://github.com/star-collector/babylon-playground and update packages there)
2. Launch app on Android
3. App crashes after attempt to render 3D scene

**Expected behavior**
App works fine, there are no crashes of any kind.

**Other**
 - Platform: Android

**Comment by ryantrem** [comment]
- What version of Babylon.js are you using?
- Do you see any warnings or errors in the metro server console?
- What errors do you see in logcat?

**Comment by star-collector** [comment]
> * What version of Babylon.js are you using?

Hmm, I noticed I used alpha.37 (maybe because of ^ prefix in package.json) of core package in latest build. Forcibly downgrading to alpha.34 seems to solve the issue with `@babylonjs/react-native 0.4.0-alpha.31`.

However, building BabylonNative from @bghgary branch of #256 manually still leads to the same crash for me in both cases. This isn't part of this issue though.

Current react-native package from npm seems to have alpha.34 in it's dependencies, which means versions above technically are not supported. If it is true, I'll close this issue. If not, the problem seems to be in `core` package and not `react-native`.

**Comment by star-collector** [comment]
As @bghgary suggested, I repost my logcat here:

<img width="1750" alt="Screenshot 2021-08-17 at 18 54 11" src="https://user-images.githubusercontent.com/19988178/129761100-f0b05eb6-5b25-4563-a8af-8ccbd1603d60.png">

**Comment by bghgary** [comment]
This is expected because BabylonReactNative hasn't been updated to the latest Babylon Native yet and there is a breaking change between 34 and 37. This will all be resolved once we update Babylon React Native to the latest. We are actively doing this right now.

**Comment by bghgary** [comment]
This should be okay now after https://github.com/BabylonJS/BabylonReactNative/pull/276.
