### ISSUE TITLE
Using loaders won't work for importing meshes other than with extension .babylon.

### ISSUE THREAD

**Issue by jayypluss** [BabylonJS/BabylonReactNative#294]
I've tried to import a file from [The Meshes Library](https://doc.babylonjs.com/toolsAndResources/assetLibraries/availableMeshes) on Babylon React Native but the loaders are not working.
The only meshes I got working were the ones with the _.babylon_ extension.

My [full code is here](https://github.com/jayypluss/babylon-native-experiment/blob/e8e99a39dfe6304eee108ccf28fcef71dbc9885a/src/components/templates/MeshTemplate.tsx).

I've installed the loaders dependency with npm using `npm install @babylonjs/loaders`. In my package.json it now shows:
`"@babylonjs/loaders": "^4.2.0",`

In my screen file I've imported the loaders like this:
`import '@babylonjs/loaders'`

And tried importing the Mesh like this:

```
  SceneLoader.ImportMeshAsync(
    null,
    'https://models.babylonjs.com/',
    'seagulf.glb',
    scene,
  ).then(result => {
    const root = result.meshes[0]
    const body = root
    body.isPickable = false

    body.setAbsolutePosition(Vector3.Zero())
    body.rotation.y = 1.55

    const deviceSourceManager = new DeviceSourceManager(engine)
    createInputHandling(deviceSourceManager, body, true).then(
      createValue => {
        console.log('createValue: ', createValue)
      },
    )
  })
```

I got this model URL from [The Meshes Library](https://doc.babylonjs.com/toolsAndResources/assetLibraries/availableMeshes) as mentioned above.
When I try importing https://assets.babylonjs.com/meshes/both_houses_scene.babylon (.babylon extension) for example, it works as expected.

I then get this error:
```
BJS - [14:23:06]: Unable to find a plugin to load .glb files. Trying to use .babylon default plugin. To load from a specific filetype (eg. gltf) see: https://doc.babylonjs.com/how_to/load_from_any_file_type
```

But also this:
```
Error: Unable to load from https://models.babylonjs.com/seagulf.glb: importMesh of undefined from undefined version: undefined, exporter version: undefinedimportMesh has failed JSON parse
```

Trying to import `https://models.babylonjs.com/seagulf.glb`
<img src="https://user-images.githubusercontent.com/17395606/137186016-c33bfe5a-b0e4-4afd-b8c1-80d7b519cfcf.png" width="200" />

Trying to import `https://assets.babylonjs.com/meshes/both_houses_scene.babylon`
<img src="https://user-images.githubusercontent.com/17395606/137186024-33b89029-b7c2-4cac-b16c-15468c095ffd.png" width="200" />

**To Reproduce**
1. Setup scene
2. Import all _@babylonjs/loaders_
3. Import glTF mesh into my created scene
4. Try running the scene
5. Mesh is not imported, "unable to find plugin" error logged

**Expected behavior**
Mesh should be imported successfully.

**Other**
 - Platform: Running from linux to Physical Android Device, Android 10, API 29

I don't know if it's actually a bug or I'm doing something wrong, either way I appreciate any help involving this, feel free to ask for more info about my code and how I'm running it. Thanks! :smile:

**Comment by bghgary** [comment]
Did you try the steps in your log to clear the cache, etc.? Also, in general, please post support questions to the forum instead of filing an issue. Thanks.
