### ISSUE TITLE
Post-optimisation PR crashing

### ISSUE THREAD

**Issue by star-collector** [BabylonJS/BabylonReactNative#299]
**Describe the bug**
@bghgary As agreed in this PR #297 , I repost bug description here. Basically, after #297 my app crashes on iOS after several seconds. No such problem seems to exist on Android. Also, problem reproduces only on real devices, iOS simulators seems to work alright.

**To Reproduce**
1. Download sample app https://github.com/star-collector/babylon-playground
2. Build and open on real iOS device (I tested on iPhone X)
3. App crashes after 5 seconds or so

**Expected behavior**
App does not crash.

**Screenshots**

Here is error call stack I get:

[call stack (1).txt](https://github.com/BabylonJS/BabylonReactNative/files/7386679/call.stack.1.txt)

<img width="921" alt="Screenshot 2021-10-21 at 09 57 19" src="https://user-images.githubusercontent.com/19988178/138227205-a0c47c2d-5ba9-43bb-83a5-c16481b08ce0.png">

<img width="1102" alt="Screenshot 2021-10-20 at 23 21 15" src="https://user-images.githubusercontent.com/19988178/138226719-3777d99d-bf6f-403c-9f49-033b4b17805c.png">

**Other**
 - Platform: iOS

**Comment by Alex-MSFT** [comment]
I noticed in your linked repo application you are using
"@babylonjs/react-native": "0.4.0-alpha.37"

This version of the package is mean to be compatible only up to are expected when using Babylon.JS version 5.0.0-alpha.50.  Can you try again using "0.4.0-alpha.38"?
