### ISSUE TITLE
Babylon React Native does not work with React Native 0.65+

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#310]
The app will crash on launch (on Android, not sure about other platforms). @jomcclan was experiencing this and we were trying to diagnose, but his Android Studio native debugging wasn't working so we didn't get very far. We should dig into this more.

This might also be related to #295, though that issue talks about a lot of different things, so hard to say for sure.

**Comment by CedricGuillemet** [comment]
Building BabylonReactNative-windows with 
```
"react": "^17.0.2",
"react-native": "^0.65.1",
"react-native-permissions": "^3.0.0",
"react-native-windows": "^0.65.6"
```
Fixed the crash at initialization for me but I get another one when create a vertexBuffer.

**Comment by awcchungster** [comment]
I can confirm similar. 

I'm actually getting a similar issue where the app crashes on launch.

iOS iPhone 13 simulator / real device. The build works fine, but it crashes on runtime.

Builds:
```
    "@babylonjs/core": "^5.0.0-alpha.60",
    "@babylonjs/react-native": "^0.4.0-alpha.45",
   "react-native": "0.66.3",
```

Logs:
```
flipper: FlipperClient::addPlugin Inspector
flipper: FlipperClient::addPlugin Preferences
flipper: FlipperClient::addPlugin React
flipper: FlipperClient::addPlugin Network
2021-12-07 16:09:59.776588-0800 babylontester[28980:5983199] [native] Running application babylontester ({
    initialProps =     {
    };
    rootTag = 1;
})
2021-12-07 16:10:29.784739-0800 babylontester[28980:5983418] [javascript] Running "babylontester" with {"rootTag":1,"initialProps":{}}
2021-12-07 16:10:29.869221-0800 babylontester[28980:5983376] [connection] nw_socket_handle_socket_event [C5:1] Socket SO_ERROR [61: Connection refused]
2021-12-07 16:10:29.869435-0800 babylontester[28980:5983383] [connection] nw_connection_get_connected_socket [C5] Client called nw_connection_get_connected_socket on unconnected nw_connection
2021-12-07 16:10:29.869567-0800 babylontester[28980:5983383] TCP Conn 0x2820a08f0 Failed : error 0:61 [61]
2021-12-07 16:10:29.913403-0800 babylontester[28980:5983418] [javascript] undefined
(lldb) 
```

The stack trace:
```
jsi::Runtime::PointerValue *JSCRuntime::cloneSymbol(
    const jsi::Runtime::PointerValue *pv) {
  if (!pv) {
    return nullptr;
  }
  const JSCSymbolValue *symbol = static_cast<const JSCSymbolValue *>(pv);
  return makeSymbolValue(symbol->sym_);
}
```

No errors being reported in Metro. I'm following the boilerplate example.

**Comment by awcchungster** [comment]
@ryantrem thanks for your work tracking and discussing this issue. Are there plans to update the library to support latest versions of react native? I'm already on 0.66.3 for my app. Appreciate your time and help

**Comment by ryantrem** [comment]
Yes, we’ve been investigating and discussing options. I think we have a plan that will work, and @CedricGuillemet will be taking on some of this work, but it will take some time.

**Comment by awcchungster** [comment]
Thanks for the fast response. Just for my own planning, should I be expected a few weeks or months before this can get PRed in?

**Comment by CedricGuillemet** [comment]
Related PRs
https://github.com/BabylonJS/BabylonReactNative/pull/322
https://github.com/BabylonJS/BabylonReactNative/pull/323
https://github.com/BabylonJS/BabylonReactNative/pull/333
https://github.com/BabylonJS/BabylonReactNative/pull/337

**Comment by bghgary** [comment]
Done.
