### ISSUE TITLE
Windows SDK upgrade

### ISSUE THREAD

**Issue by tymlipari** [BabylonJS/BabylonReactNative#344]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
The latest Github Actions agents for Windows no longer have the 10.0.18362.0 SDK available as it's several major versions behind. The related projects should be updated to target a newer version of the Windows SDK. Unfortunately upstream dependencies from react-native-windows (at least for 0.64) also include VS projects targeting that same build number.

**To Reproduce**
1. Clone the repository for Windows
2. Ensure the 18362 SDK is uninstalled and a newer version is installed
3. Observe the React Native build fail when running `npm run windows` for the Playground project targeting 0.64.

**Suggested fix**
For 0.64 it's unlikely RNW will update their package, but the CI builds can be scripted to scan all of the *.vcxproj files referenced  (including those from npm modules) from the solution file and update their `<WindowsTargetPlatformVersion/>` elements to target a newer SDK version. This will have no runtime impact as all Windows SDKs are backwards compatible, but will allow the project to build with later SDKs.

**Comment by bghgary** [comment]
Duping with #507
