### ISSUE TITLE
protocol version mismatch 2 (Native) !== 4 (JS)

### ISSUE THREAD

**Issue by f4z3k4s** [BabylonJS/BabylonReactNative#354]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
I think this is not a bug, @babylonjs/react-native just hasn't yet followed the changes going on in @babylonjs/core. [This](140ce5e6a36a0315dc67236bbf0e7238e2ab8c4b) latest commit that this package works with,  (release of @babylonjs/core@v5.0.0-beta.11)

**To Reproduce**
1. Install latest rc from @babylonjs/core
2. Try to render anything

**Expected behavior**
@babylonjs/react-native works with latest @babylonjs/core

I don't intend this as a bug report, sorry if I chose the wrong forum to mark this, but people will find it here the best probably. I know that you'll eventually follow ProtocolVersion of @babylonjs/core. I just intend to mark this issue for people that update their @babylonjs/core version automatically and break their app, and don't know where to start. Just downgrade @babylonjs/core (and loaders) to v5.0.0-beta.11 and it will work with @babylonjs/react-native@0.64.0-alpha.47 until this package catches up.

Edit:

Probably this should be updated in the package.json of @babylonjs/react-native as peerDependency
```
"@babylonjs/core": "^5.0.0-alpha.65",
```
will break things for many people.

**Comment by bghgary** [comment]
Closing as we have a table that describes the compatibility between versions.
