### ISSUE TITLE
VisualStudio 2022 support

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonReactNative#358]
I did a quick test (unfortunate) building BRN with VS2022 and got compilation error 
```
E:\dev\babylon\BRNDeploy064\Apps\Playground\Playground\node_modules\react-native-windows\Mso\dispatchQueue\dispatchQueue.h(728,17): error C2607: static assertion failed
       [E:\dev\babylon\BRNDeploy064\Apps\Playground\Playground\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
```

I don't know if it's related to VS, Windows SDK or something else. Anyway, a test with newest VS might be a good idea.

**Comment by bghgary** [comment]
I'm not sure this belongs in BabylonReactNative repo. We already know VS2022 doesn't work in BabylonNative repo. Not sure there is an issue on it though.

**Comment by CedricGuillemet** [comment]
Problems won't be the same because of dependencies (react native windows and other packages). It won't be as hard/ time consuming with BN.

**Comment by CedricGuillemet** [comment]
When trying the playground build/test githubaction with VS2022, I got this error:
```
D:\a\BabylonReactNative-1\BabylonReactNative-1\Playground\node_modules\react-native-windows\Microsoft.ReactNative\Utils\Helpers.h(21,8): error C2187: syntax error: 'typename' was unexpected here (compiling source file Modules\LogBoxModule.cpp) [D:\a\BabylonReactNative-1\BabylonReactNative-1\Playground\node_modules\react-native-windows\Microsoft.ReactNative\Microsoft.ReactNative.vcxproj]
```
It's fine with VS2019

**Comment by bghgary** [comment]
Based on #656, it seems like this works already.
