### ISSUE TITLE
iOS: noticeable stutter & frame drop with complex models when touching screen 

### ISSUE THREAD

**Issue by jonklein** [BabylonJS/BabylonReactNative#387]
**Describe the bug**
When rendering a somewhat complex scene, touch start and end events trigger a noticeable stutter or frame drop, even if there is no touch handler configured.

**To Reproduce**
1. With the Playground app in this repo, load a more complex model than the default (https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/2CylinderEngine/glTF/2CylinderEngine.gltf"
2. Disabled the included touch handing just to ensure it's not related (comment out the call to `deviceSourceManager.onDevice`)
3. Run the sample, touch the screen rapidly.
4. Framerate drops from 60 fps down to 10 fps or below depending on how quickly you tap.

**Expected behavior**
The rendering should not stutter or drop frame when touches start and end, particularly if there is no user processing.
**Other**
 - Platform: iOS

*edited to add* Most noticeable on device, as opposed to simulator.

**Comment by CedricGuillemet** [comment]
Related : https://github.com/BabylonJS/BabylonNative/issues/1047

**Comment by CedricGuillemet** [comment]
Some picking is done when a touch occurs. To avoid it, add this to your JS code:
```
scene.pointerUpPredicate = ()=> false;
scene.pointerDownPredicate = ()=> false;
scene.pointerMovePredicate = ()=> false;
```

**Comment by bghgary** [comment]
Keeping open to discuss with Babylon.js team to see if we can somehow disable picking by default.

**Comment by PolygonalSun** [comment]
@PolygonalSun self-tag

**Comment by bghgary** [comment]
@PolygonalSun Can you verify this is fixed after your picking changes?

**Comment by CedricGuillemet** [comment]
Talked offline with Dave. Closing.
