### ISSUE TITLE
Source of performance issues compared to other solutions

### ISSUE THREAD

**Issue by pot2mayo** [BabylonJS/BabylonReactNative#405]
Hi

I evaluating several 3D rendering solution for a 3D game in react native.
`Babylon.js React Native` is one of them, along with `Expo-three` and `Unity WebGL` build in a RN webview.

I noticed that both `Babylon.js React Native` and `Expo-three` have significantly lower performance (about half the framerate) compared to a native Unity build using the same scene.

I understand that react native adds some overhead for the scene setup and asset processing, but since all graphics APIs are backed up by purely native GL calls under the hood, I don't understand such difference in performance for the rendering itself.

Could you provide some hints on why we have such performance hit for react native solutions?

Thanks a lot!

**Comment by bghgary** [comment]
Can you provide more info? What kind of scene you are trying to render?

**Comment by pot2mayo** [comment]
@bghgary 
Thank you for your reply!
I'm trying to render a 3D environment made of several objects with a total of 70 000 vertices.
Objects have simple lambert shading with only a base color, no textures.
For the scene setup I re-used the provided [Playground sample scene](https://github.com/BabylonJS/BabylonReactNative/tree/master/Apps/Playground) as-is and I just plugged in my model without making any other changes.
I am testing on an Android device (OnePlus 8 Pro, snapdragon 865) build in release mode.

The scene renders at 20fps when zooming-in and most objects are being culled out of the camera frustrum, and 11fps when zooming out with all the objects in the scene visible.

A similar scene made with `Expo-three` gives me about the same performances.

For reference I made the scene scene in Unity and tried a native Android build which runs at 60fps and there is plenty of room for more.

I also tried a Unity WebGL build and render it in a [react native webview](https://reactnative.dev/docs/0.61/webview) and it also runs at full speed.

I am going to try to merge all the objects in my scene in one single object to see how it impacts performances. My guess is that it will lower the number of draw calls and maybe relief the load a little.

Thanks!

**Comment by bghgary** [comment]
Would you be able to share the model? This would be the best way to help solve it. Is that possible? You can share it privately if you want via a private message on our forum if that's better.

I have a OnePlus 8 which has similar specs, so I can probably repro.

**Comment by pot2mayo** [comment]
@bghgary 
Thank you for your suggestion.
I sent a private message via the forum with link to download the model data and a video capture of how it renders on my phone.

Since the forum did not allow me to message you only privately for some reason (got an error message on send) I messaged it to all moderators, I hope that's ok and you'll get the message.

**Comment by bghgary** [comment]
I haven't completely confirmed this, but it is very likely that this scene is slow because there are many nodes. JIT is disabled for React Native and it will run slower for this type of scene.

**Comment by pot2mayo** [comment]
@bghgary 
Thanks for your feedback.
There is indeed a lot of objects in this scene.
We'll try to merge them all into one and see how it impacts the performances

**Comment by bghgary** [comment]
You're welcome. We are eventually going to investigate if we can still make the rendering this type of scene fast without JIT, but that will take a bit of research and effort. Are you okay if we close this issue? Also, please use the forum next time for this type of question :-)

**Comment by pot2mayo** [comment]
@bghgary 
Sure, let me close this issue.
Please keep me posted if you have any update.
Thanks again
