### ISSUE TITLE
XR Session - Accessing Raw Camera Data

### ISSUE THREAD

**Issue by muta93srb** [BabylonJS/BabylonReactNative#418]
**Is your feature request related to a problem? Please describe.**
I need to get raw camera data (without meshes) in XR session so i can process the image further and create some meshes based on that processing.

**Describe the solution you'd like**
I need to access raw camera data before Babylon Meshes are rendered over it. Any format and way of accessing the data would be great.

**Describe alternatives you've considered**
[Snapshots](https://github.com/BabylonJS/BabylonReactNative/blob/c4ce035444c4fdb4deaa053856e318038668cbfc/Modules/%40babylonjs/react-native-iosandroid/android/src/main/java/com/babylonreactnative/EngineView.java#L161) access without Babylon Meshes would be great too.

**Additional context**
Discussion on [forum](https://forum.babylonjs.com/t/current-state-of-secondary-views-webxr-recording/27293/14)
WebXR feature: https://immersive-web.github.io/raw-camera-access/
How it is managed in WebXR: https://github.com/immersive-web/raw-camera-access/blob/main/explainer.md

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature and WebXR supports this.
