### ISSUE TITLE
Performance of BabylonJS in webview vs BabylonReactNative

### ISSUE THREAD

**Issue by Tom-CrowdSurf** [BabylonJS/BabylonReactNative#427]
Hello,
Thanks for creating this BabylonReactNative.  We have an app in development that currently uses BabylonJS in a Webview and it works well - but we're always trying to eek out a bit more performance. 
Is it worth the time converting our codebase to use BabylonReactNative instead of a webview - is it more performant and what are the other benefits?
Thanks!
Tom

**Comment by ryantrem** [comment]
Hey @Tom-CrowdSurf - glad to hear you are considering Babylon React Native! Take a look at this Babylon Native doc: https://github.com/BabylonJS/BabylonNative/blob/master/Documentation/WhenToUseBabylonNative.md. It helps understand the benefits of Babylon Native / Babylon React Native, when to use it, and a little bit about what to expect from a performance standpoint. If you have more questions that the doc doesn't answer, lets get a discussion started on the [forum](https://forum.babylonjs.com). :)
