### ISSUE TITLE
Added IOS Simulator arm64 binaries to npm packages

### ISSUE THREAD

**Issue by SergioRZMasson** [BabylonJS/BabylonReactNative#451]
## Context

We currently ship @babylonjs/react-native-iosandroid packages with only x86_64 binaries for the IOS Simulator platform. This makes users that consume the package on arm64 MacBook's to be forced to manually modify their Podfile and .xcodeproj to force project to be compiled only for x86_64 Simulator and run under Rossetta. If arm64 binaries were provided I believe everything would work out of the box. 

## Improvement

Include arm64 IOS Simulator binaries in packages 

- @babylonjs/react-native-iosandroid-64
- @babylonjs/react-native-iosandroid-65
- @babylonjs/react-native-iosandroid-69

**Comment by ryantrem** [comment]
If I recall I think there is an issue with the way we currently create the libs... we use lipo to merge the x86 and arm libs into a single lib, and the correct architecture is chosen when linking later. However, I believe lipo can't merge two different arm libs (device and simulator). I think we have to switch to an xcframework or something.

**Comment by stetbern** [comment]
Xcode will stop supporting Rosetta in 14.3, I think this issue will be important for many developers soon: https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes

**Comment by SergioRZMasson** [comment]
@bghgary @CedricGuillemet  for visibility.

**Comment by bghgary** [comment]
https://forum.babylonjs.com/t/babylonreactnative-building-for-ios-simulator/28506

**Comment by ChaimMark** [comment]
Do you happen to have any updates on the adding arm binaries?

**Comment by CedricGuillemet** [comment]
> Do you happen to have any updates on the adding arm binaries?

Sorry, no update yet. But it's still on our radar.

**Comment by bghgary** [comment]
Closing for now. Reopen if we want to support this feature.

**Comment by bghgary** [comment]
@CedricGuillemet @ryantrem Is this handled by the xcframework work that @okwasniewski is doing?

**Comment by antoine-wbr** [comment]
Any news on this effort ? I'm still unable to test on simulator but now my app crashes at startup when I use a real device...
If I remove Babylon Native my app starts just fine. So, I know it's related to babylon native...

**Comment by kessenma** [comment]
ya I am getting this issue too on a m1 MacBook right now too. seems like it should not be closed?
