### ISSUE TITLE
PDB for Windows NPM releases

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonReactNative#453]
.pdb are not present in BRN npm for Windows. 
I guess it's a choice or npm would be >500Mb. 
You have to build BRN locally and copy .lib/.pdb manually if you need to debug. 

We need .pdb to be present somehow so it's easier for the dev team or users/contributor to test and debug.

I have 2 proposals to achieve this:

- Improve the build system/npm so NPM will not contain everything but it will only download at installation time a sub-package. I talked briefly with @RaananW about that. I think it's the way to go but it needs a lot of work and testing. This way, we are not tight to the 200Mb limit.
- Provide the .pdb as a downloadable artifact. Easier to do but you have to be logged in Github to be able to download them. Moreover, you will have to go the the action corresponding to the npm publishing, donwload an unzip it manually. The artifact are retained for 90days.

**Comment by bghgary** [comment]
We would probably fix this by putting pdbs into separate packages. Closing in favor of #614
