### ISSUE TITLE
Error/Crash app when using GLTF 1.0

### ISSUE THREAD

**Issue by cuog1598** [BabylonJS/BabylonReactNative#459]
When I try to setup the  [sample repos](https://github.com/BabylonJS/BabylonReactNativeSample). I checked on emulator ios 15.5. when i change the sample gltf url to [gltf 1.0 file](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/1.0/Duck/glTF/Duck.gltf). I haved Followed the setup steps in the **Sample repos**.

Error:
 ERROR  BJS - [15:07:22]: Unable to compile effect:
 ERROR  BJS - [15:07:22]: Uniforms:  u_ambient, u_emission, u_light0Color, u_light0Transform, worldView, u_normalMatrix, projection, u_shininess, u_specular, u_diffuse
 ERROR  BJS - [15:07:22]: Attributes:  normal, position, uv
 ERROR  BJS - [15:07:22]: Defines:
#define NUM_BONE_INFLUENCERS 0
#define NUM_MORPH_INFLUENCERS 0
 ERROR  BJS - [15:07:22]: Error: Exception in HostFunction: Unrecognized uniform type.
 ERROR  TypeError: defines.markAsUnprocessed is not a function. (In 'defines.markAsUnprocessed()', 'defines.markAsUnprocessed' is undefined)
 ERROR  Error: Exception in HostFunction: defines.markAsUnprocessed is not a function. (In 'defines.markAsUnprocessed()', 'defines.markAsUnprocessed' is undefined)
<img width="597" alt="image" src="https://user-images.githubusercontent.com/45631763/189605484-3ab655e5-8c57-4e70-a6db-c1e13c46f10c.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/45631763/189605583-384434bf-796c-4f53-9889-f7a1e123016d.png">

**Other**
I have try with another gltf 1.0 like [my gltf 1.0 file](https://raw.githubusercontent.com/cuog1598/RentalCarRn/master/willy/willy.gltf)
**My app has been crashed**
I also try playground too and that not help me to render gltf file

**Comment by bghgary** [comment]
I don't anyone has tried with a glTF 1.0. Can I ask why you want to use glTF 1.0? Hardly anyone uses this anymore.

**Comment by cuog1598** [comment]
> I don't anyone has tried with a glTF 1.0. Can I ask why you want to use glTF 1.0 and not 2.0? Hardly anyone uses 1.0 anymore.
It's just that I got gltf 1.0 from my customer and asked me to show this one. so can i have any way to render glTF 1.0.
I also know glTF 1.0 too old and no one wants to use them anymore... I also want they change and use 2.0 but the answer is "_However when they went to GLTF 2.0 they try to make it more open, so they remove the possibility to write shader (now it also work with Direct X)_" .
pls ask me if have any solution.
thanks...

**Comment by bghgary** [comment]
It's an issue with the shader compiler in Babylon Native. We don't officially support glTF 1.0 right now in Babylon Native, so it might take some time before we fix this problem.

**Comment by bghgary** [comment]
Closing for now. If you really need glTF 1.0 support, please reopen.
