### ISSUE TITLE
Some users report issue using it with react native 0.69 and 0.65

### ISSUE THREAD

**Issue by SergioRZMasson** [BabylonJS/BabylonReactNative#469]
**Describe the bug**
Some consuming the BabylonReactNativeSample project with react native 0.69 are reporting issue "Unexpected token '=' ". This issue seems to happen when one addes the following line to the App.tsx file:

```
const engine = useEngine();
```

**To Reproduce**
1. git clone https://github.com/BabylonJS/BabylonReactNativeSample.git
2. git checkout react-native-0-69
3. npm install
4. npm run android

**Screenshots**

![react_native_69_issue](https://user-images.githubusercontent.com/97050577/194326295-d6f970d3-87da-4bf0-890a-e795b6a8243a.png)

**Other**
 - Platform: [e.g. Win32, UWP, HoloLens, Android, iOS]
 
 **User reported issues**
 - https://github.com/BabylonJS/BabylonReactNativeSample/issues/9

**Comment by CedricGuillemet** [comment]
I'm taking a look and I may have found something:
```
error node_modules\@babylonjs\core\Compute\computeShader.js: Unexpected token: operator (=) in file node_modules\@babylonjs\core\Compute\computeShader.js at 69:31. 
```

**Comment by thomlucc** [comment]
Fixed!
