### ISSUE TITLE
this._xhr.getResponseHeader is not a function.

### ISSUE THREAD

**Issue by Bruce-zxy** [BabylonJS/BabylonReactNative#474]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
When I pull down the code of BabylonReactNativeSample and run it, the console reports an error, the error shows that this._xhr.getResponseHeader is not a function.

**To Reproduce**
1. clone the [BabylonReactNativeSample](https://github.com/BabylonJS/BabylonReactNativeSample);
2. yarn
3. cd ios && pod install
4. yarn start
5. yarn ios --simulator "iPhone 14 Pro"

**Expected behavior**
I want the example to work.

**Screenshots**
<img width="606" alt="image" src="https://user-images.githubusercontent.com/22904758/194771685-3fa92421-2139-41fa-aad4-e81253772ea0.png">

**Other**
 - Platform: [iOS]
 - Nodejs: [16.17.1]
 - Npm: [8.15.0]

**Comment by ryantrem** [comment]
Fixes are under way:
https://github.com/BabylonJS/BabylonNative/pull/1144
https://github.com/BabylonJS/BabylonNative/pull/1149

**Comment by Bruce-zxy** [comment]
> Fixes are under way: [BabylonJS/BabylonNative#1144](https://github.com/BabylonJS/BabylonNative/pull/1144) [BabylonJS/BabylonNative#1149](https://github.com/BabylonJS/BabylonNative/pull/1149)

Thanks a lot.

**Comment by CedricGuillemet** [comment]
Hi @Bruce-zxy latest package v 1.4.0 should have the fix. Let me know if you still have an issue.
