### ISSUE TITLE
IWebXRHitTestOptions should expose options to hit test against Planes, Points etc

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonReactNative#53]
When hit testing against real world geometry (through ARKit/ARCore), the hit test seems to be very specific to a particular implementation. 

On the ARCore implementation [Source [link](https://github.com/BabylonJS/BabylonNative/blob/master/Dependencies/xr/Source/ARCore/XR.cpp)]:

```
            // Iterate over the results and pull out only those that match the desired TrackableType.  For now we are limiting results to
            // just hits against the Plane, and further scoping that to Poses that are contained in the polygon of the detected mesh.
            // This is equivalent to XRHitTestTrackableType.mesh (https://immersive-web.github.io/hit-test/#hit-test-trackable-type-enum).
```

For apps looking to build a React Native app using BabylonReactNative as its XR abstraction, it is desirable to be able to configure the specifics of what hit testing would be against. E.g. Similar to Unity's ARFoundation [XRRaycastHit ](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@4.0/api/UnityEngine.XR.ARSubsystems.XRRaycastHit.html)object

**Comment by hendryems** [comment]
Note: Hit testing against feature points itself isn't necessarily impactful but for our scenarios, we would like to have a less restrictive hit testing implementation, e.g. using `XRHitTestTrackableType.plane` specifically.

**Comment by Alex-MSFT** [comment]
This has been implemented in BabylonNative, and BabylonReactNative.  We just need to get a new package version of Babylon.js and pull this into BabylonReactNative.
