### ISSUE TITLE
Error when trying to run AR demo code IOS

### ISSUE THREAD

**Issue by ALMALEVISOL** [BabylonJS/BabylonReactNative#546]
Hi Friends!

Im new to BabylonReactNative and this is my first issue, i just trying to run basic demo AR feature in my app in IOS (URL below) 
https://github.com/BabylonJS/BabylonReactNativeSample/blob/main/App.tsx
but it gives me this error when i toggle XR in order to see a 3D Model in AR: 

```
 LOG {"error": 9}
 LOG  undefined
```
 
The weird thing it is this error only shows in IOS in android works flawlessly.
Doing some research it seems that the error is in this code block, specifically the first line `initializeSessionAsync`
It seems it cannot get the xrSession but due remote debugger is not supported i can not get inside the code.

```
// make sure that the session mode is supported
        try {
            await this.sessionManager.initializeSessionAsync(sessionMode, sessionCreationOptions);
            ...rest of the code
        }
        catch (e) {
            console.log(e);
            console.log(e.message);
            this._setState(WebXRState.NOT_IN_XR);
            throw e;
        }
```

Under node_modules/@babylonjs/core/XR/webXRExperienceHelper.js

I hope you can help me, because i am not able to find what does error number 9 is...
Sorry if i miss something and my bad english. :)

**Comment by bghgary** [comment]
Please use the [forum](https://forum.babylonjs.com/) for troubleshooting. Are you able to get a call stack for the error?

**Comment by ALMALEVISOL** [comment]
kkk
