### ISSUE TITLE
README should be updated to include instructions to correctly configure Android Emulator

### ISSUE THREAD

**Issue by hendryems** [BabylonJS/BabylonReactNative#55]
BabylonReactNative requires GLES3 on Android. Otherwise one will run into the following errors when deploying it onto the Android Emulator:

```
D/: F:/Source/Repos/BabylonReactNative/Apps/Playground/node_modules/@babylonjs/react-native/submodules/BabylonNative/Dependencies/bgfx.cmake/bgfx/src/renderer_gl.cpp (5638): BGFX CHECK glTexParameteri(targetMsaa, 0x813D, numMips-1); GL error 0x500: GL_INVALID_ENUM
A/libc: Fatal signal 5 (SIGTRAP), code 128 (SI_KERNEL), fault addr 0x0 in tid 1398 (mqt_js), pid 1349 (com.playground)
```

Instructions should be updated to clarify Android Emulator specific setup:
1. The GLES3 setting needs to be enabled from the Android Emultor; not the Virtual Device Settings (which needs to be set to `Automatic`):
![image.png](https://images.zenhubusercontent.com/5f1231a10ac79462fe3b268a/dbb6e253-0cac-4cbd-abb2-391f768dfb96)
2. Ensuring that the right `Google Play Services for AR` is installed on the Emulator per instructions [here](https://developers.google.com/ar/develop/java/emulator#update-arcore).

**Comment by CedricGuillemet** [comment]
There is already a doc page on setting emulator for Android. I've opened a PR with these infos : https://github.com/BabylonJS/BabylonNative/pull/438
