### ISSUE TITLE
Crash after exiting XR and then toggling the view

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonReactNative#57]
If the view is recreated after having entered and exited XR, the Playground app crashes (Android and iOS).

Repro steps:
1. Start the Playground app on a device (haven't tested on emulator).
2. Enter XR mode.
3. Exit XR mode.
4. Click the button at the top to remove the EngineView.
5. Click the button at the top to add (reinitialize) the EngineView.
6. Observe the crash.

**Comment by CedricGuillemet** [comment]
For Android, the PR is here : https://github.com/BabylonJS/BabylonNative/pull/342

**Comment by CedricGuillemet** [comment]
I have a strange issue on iOS device after disabling/enabling engineView. It looks like the metal memory layout is totally wrong. No crash nor console message but something is definitely going wrong.
<img width="1680" alt="Screenshot 2020-07-28 at 17 21 35" src="https://user-images.githubusercontent.com/1312968/88692747-b7ac1480-d0fe-11ea-8d27-4bb8526c8047.png">

**Comment by CedricGuillemet** [comment]
This issue is fixed by https://github.com/BabylonJS/BabylonNative/pull/431
Doing a mismatch of MSAA with reset (enable at startup then reset without msaa) caused that glitched view.

**Comment by bghgary** [comment]
Fixed!
