### ISSUE TITLE
iosandroid packages do not include jniLibs for x86_64 ABI

### ISSUE THREAD

**Issue by ivalduan** [BabylonJS/BabylonReactNative#575]
The current npm packages do not include x86_64 files for Android.

This is a problem for the latest Emulator System Images that are only provided under that ABI:

![image](https://user-images.githubusercontent.com/2285554/236681226-efcf8b17-77ea-4f21-b171-59d0ee1833e9.png)

When we try to execute an app on the emulator with these systems it crashes due to the missing lib:

![image](https://user-images.githubusercontent.com/2285554/236681491-e8c4c809-c48b-4ba3-8db8-29a453e83355.png)

**Comment by CedricGuillemet** [comment]
I can confirm. Working on a fix now...
