### ISSUE TITLE
React-Native 0.71: TypeError: Cannot read property 'initialize' of null

### ISSUE THREAD

**Issue by hjopel** [BabylonJS/BabylonReactNative#583]
**Describe the bug**
When running `npm run ios` or `npx react-native run-ios` after following the official [react-native guide](https://reactnative.dev/docs/environment-setup) and then the [babylonjs guide](https://github.com/BabylonJS/BabylonReactNativeSample/blob/main/CREATE.md), I get the following issue:

```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'initialize' of null
TypeError: Cannot read property 'initialize' of null
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.starter:308087:39)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.starter:20416:26)
```

**To Reproduce**
Either follow the two guides mentioned above or checkout [my repo](https://github.com/hjopel/rn-babylon).

Run `npm run ios` (according to the babylon docs) or `npx react-native start` in a separate terminal and then `npx react-native run-ios`. 

**Expected behavior**
I expect the babylon scene to be rendered without any errors.

**Screenshots**
<img width="500" alt="image" src="https://github.com/BabylonJS/BabylonReactNative/assets/70332133/70feb0e5-95f1-4d5d-8255-dc87797eba77">

**Other**
 - macOS M2
```
 "dependencies": {
    "@babylonjs/core": "^5.42.2",
    "@babylonjs/loaders": "^5.42.2",
    "@babylonjs/react-native": "^1.6.1",
    "@babylonjs/react-native-iosandroid-0-71": "^1.6.1",
    "react": "18.2.0",
    "react-native": "0.71.11"
  }
```

**Comment by hjopel** [comment]
ah I see. after running `pod install` in the `ios` directory I don't get this error anymore. Thank you @ryantrem !

**Comment by Rooban19** [comment]
This issue is happening on android as well. Any ideas to fix that ?

**Comment by ryantrem** [comment]
Is it the exact same error?
Is it specifically with RN 0.71?
Are you seeing this in the BRN Playground app or your own app?

**Comment by Rooban19** [comment]
It works after running `npx react-native run-android`

**Comment by seasia-developer** [comment]
I have the same issue even though I have installed the pods successfully.
  "@babylonjs/core": "^8.26.0",
    "@babylonjs/loaders": "^8.26.0",
    "@babylonjs/react-native": "^1.9.0",
    "react": "18.2.0",
    "react-native": "0.74.7"

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/e7192d00-b198-4ded-ada0-8fb4e2dd98cf" />

**Comment by CedricGuillemet** [comment]
We are in the process of updating the package with a new architectured npm, can you please try with this npm tgz ? https://github.com/BabylonJS/BabylonReactNative/actions/runs/16596899692/artifacts/3638977007
