### ISSUE TITLE
Particle System not being rendered

### ISSUE THREAD

**Issue by Laegel** [BabylonJS/BabylonReactNative#586]
**Describe the bug**
Particle system included in a scene seems to fail silently.

**To Reproduce**

The scene from [the following PG](https://playground.babylonjs.com/#I4KUSG#2) works as expected in the browser but, from the mobile app, everything is rendered except the particle system. There are no errors and the texture is loaded but nothing happens.

**Expected behavior**
Particle system should be rendered.

**Other**
 - Platform: Android 9
- @babylonjs/core 5.42.2

Please let me know if you need anything else. Hopefully, this is just me misusing the particle system. :sweat_smile:

**Comment by CedricGuillemet** [comment]
Particle rendering on Native is work in progress. Some issues are already known : https://github.com/BabylonJS/BabylonNative/issues/1041

@SergioRZMasson is working on the feature

**Comment by bghgary** [comment]
Closing in favor of the BabylonNative issue.
