### ISSUE TITLE
BabylonNative.h is missing in @babylonjs/react-native v1.7.7 and 1.7.8.

### ISSUE THREAD

**Issue by WayneKim92** [BabylonJS/BabylonReactNative#620]
**Describe the bug**
BabylonNative.h is missing in @babylonjs/react-native v1.7.7 and 1.7.8.
Due to this issue, when building an iOS app, a build error occurs saying that BabylonNative.h cannot be found.

**To Reproduce**
- yarn add @babylonjs/react-native@v1.7.7
- Clean Pod file
- Pod install
- build iOS app

**Expected behavior**

**Screenshots**

**Other**
 - Platform: iOS

**Comment by bghgary** [comment]
@CedricGuillemet FYI

**Comment by WayneKim92** [comment]
@chenkuangkuang thanks. it works to me. 

![image](https://github.com/BabylonJS/BabylonReactNative/assets/75321423/bd1c8713-f7f9-4795-8c59-214a58a6917d)

**Comment by WayneKim92** [comment]
ummmmm... Build and run was successful, but an execution error occurred. lol~

![image](https://github.com/BabylonJS/BabylonReactNative/assets/75321423/84f06e15-dbda-43a5-8575-868cbbfe482c)

**Comment by CedricGuillemet** [comment]
I believe this issue has been introduced with https://github.com/BabylonJS/BabylonReactNative/pull/616
I'm taking a closer look.

**Comment by CedricGuillemet** [comment]
> @CedricGuillemet can you help this [#620 (comment)](https://github.com/BabylonJS/BabylonReactNative/issues/620#issuecomment-1829046809)?

Let me first fix the package, then I'll try to repro the crash.

**Comment by CedricGuillemet** [comment]
I've fixed the issue with package 1.8.0 and now I can repro #622 
Closing.
