### ISSUE TITLE
How can I create a video from animated 3d model ?

### ISSUE THREAD

**Issue by chenkuangkuang** [BabylonJS/BabylonReactNative#621]
Is there a way to made a video from animated 3d model ? I noticed this(https://playground.babylonjs.com/#M2JYAK), but I cannot find anything useful in this package.

**Comment by ryantrem** [comment]
Hi @chenkuangkuang - since this is more of a question than a bug, will you re-ask this on the [BJS forum](https://forum.babylonjs.com/)? You can ping me there and I will provide some context and thoughts on this.
