### ISSUE TITLE
paused and show "Failed to create Fragment shader"

### ISSUE THREAD

**Issue by chenkuangkuang** [BabylonJS/BabylonReactNative#622]
My app build successful, and run on my phone. But then xcode shows "paused" and the logout shows "Failed to create Fragment shader".

Anyone help?

**Comment by bghgary** [comment]
Please ask questions on our forum: https://forum.babylonjs.com.

Can you give a bit more information? Android/iOS? Are you running the Playground app? Can you provide a repro?

**Comment by CedricGuillemet** [comment]
I can repro with package 1.8.0. I'm working on a fix.

**Comment by CedricGuillemet** [comment]
There is a PR open. I'll kick a new package release once merged : https://github.com/BabylonJS/BabylonReactNative/pull/626

**Comment by CedricGuillemet** [comment]
1.8.1 package is building. Check this page to know when it's available: https://www.npmjs.com/package/@babylonjs/react-native/v/1.7.8?activeTab=versions 
It should fix the shader crash. If not, please re-open this issue.
