### ISSUE TITLE
v1.8.2 breaks iOS Texture rendering

### ISSUE THREAD

**Issue by undeaDD** [BabylonJS/BabylonReactNative#638]
**Describe the bug**
- Textures were rendering fine with v1.8.1 on iOS.
- Downgrading from 1.8.2 to 1.8.1 breaks the Android App though ( blue background ).
- Updating to 1.8.2 makes all Meshes invisible on iOS ( / not render correctly ).

Minimal demo project is on its way ( will update soon )

**To Reproduce**
1. enable XR image tracking and render <EngineView>
2. register tracking images and create sphere with texture
3. iOS: texture renders fine on 1.8.1 but not in 1.8.2
3. Android: texture renders fine on 1.8.2 but shows the blue background on 1.8.1

**Expected behavior**
iOS Textures should render correctly and should not be invisible

**Screenshots**
( will update soon )

**Other**
 - Platform: iOS + macOS ( running Xcode & Android )

**Comment by CedricGuillemet** [comment]
Hi @undeaDD 
issue with Android and 1.8.1 is expected. There was issue with backbuffer swapping.
So, 1.8.2 is the package to use.
iOS issue is not expected. Can you please provide a script that repro the issue?
Also, do you get any error/warning in the console? 
Did you try to do a GPU capture with Xcode?
