### ISSUE TITLE
Dependency Conflict When Initializing App

### ISSUE THREAD

**Issue by in-the-ocean** [BabylonJS/BabylonReactNative#644]
**Describe the bug**
I was following this instruction to set up an app: https://github.com/BabylonJS/BabylonReactNativeSample/blob/main/CREATE.md
And it tells me that there is conflicting dependencies on @babylonjs/core.

I think the latest of @babylonjs/core is 7.3.1 but we are still using 6.14.0 here. Overring the @babylonjs/core to use 6.14.0 in package.json helps resolve, but I think the correct fix would be to upgrade this package to use 7.3.1.

**To Reproduce**
1. `npx react-native@latest init AwesomeProject`
2. `npm i @babylonjs/react-native @babylonjs/react-native-iosandroid-0-71 @babylonjs/core @babylonjs/loaders`
3. See the error
![Screenshot 2024-04-19 at 21 57 07](https://github.com/BabylonJS/BabylonReactNative/assets/46516657/43d67b66-ec94-49db-b6ad-b6acf8ed5b34)

**Expected behavior**
The npm install should complete without errors.

**Comment by ryantrem** [comment]
@in-the-ocean we are actively working on getting Babylon Native and Babylon React Native updated to work with BJS 7+. There were some unexpected challenges so it is taking longer than expected, but it should be done soonish! In the meantime, you will need to install a 6.* version of BJS, e.g. `npm i @babylonjs/react-native @babylonjs/react-native-iosandroid-0-69 @babylonjs/core@6.49.0 @babylonjs/loaders@6.49.0`
