### ISSUE TITLE
Building for 'iOS-simulator', but linking in object file (.../node_modules/@babylonjs/react-native-iosandroid-0-71/ios/libs/libBabylonNative.a[arm64][2](BabylonNative.o)) built for 'iOS'

### ISSUE THREAD

**Issue by thechaudharysab** [BabylonJS/BabylonReactNative#650]
**Describe the bug**

I created a react-native app and was testing on android, until I decided to test on iOS simulator as well. I remember there is no additional step for iOS like it was for Android Emulator **Renderer maximum**. So I cleaned the project, did a `pod install` on iOS and then opened XCode to run it on iPhone 15 simulator and I got this error below:

Getting the error below when I run on iOS:

```
Building for 'iOS-simulator', but linking in object file (/MY_PROJECT_PATH/node_modules/@babylonjs/react-native-iosandroid-0-71/ios/libs/libBabylonNative.a[arm64][2](BabylonNative.o)) built for 'iOS'
```

The same code works find on Android.

**To Reproduce**

Here are the dependencies I have:

```
    "@babylonjs/core": "^7.12.0",
    "@babylonjs/loaders": "^7.12.0",
    "@babylonjs/react-native": "^1.8.5",
    "@babylonjs/react-native-iosandroid-0-71": "^1.8.5",
    "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-permissions": "^4.1.5"
```

I'm testing it with a mac with Apple chip.

The code I've in react-native is:

```

const basicGLTFURL = '';

  const renderClient = () => {
    SceneLoader.LoadAsync(basicGLTFURL, undefined, engine).then((loadScene) => {
      if (loadScene) {
        setScene(loadScene);
        // Light
        const light = new HemisphericLight("light", new Vector3(0, 1, 0), loadScene);
        light.intensity = 1.0;

        // Camera
        const camera = new ArcRotateCamera("camera", -Math.PI / 2, Math.PI / 2, -6, new Vector3(0, 2, 0), loadScene, true);
        setCamera(camera);
      } else {
        console.error("Error loading loadScene.");
      }
    }).catch((error) => {
      console.error("Error loading scene: ", error);
    });
  };
  
  useEffect(() => {
    if (engine) {
      renderClient();
    }
  }, [engine]);
  
    return (
    <View style={styles.container}>
      <EngineView camera={camera} displayFrameRate={true} />
      )
  
```

1. Install the above
2. Do a `pod install`
3. Open XCode and run the app on iOS simulator

**Expected behavior**
To work on iOS the same way it does on Android.

**Other**
- It works find on Android emulator. I don't have an apple device but was trying it on iOS simulator and got a second error that reads: `Linker command failed with exit code 1 (use -v to see invocation)`

**Comment by ryantrem** [comment]
Are you running on a Mac with Apple silicon (e.g. M1/M2/M3, not an Intel chip)?

**Comment by thechaudharysab** [comment]
> Are you running on a Mac with Apple silicon (e.g. M1/M2/M3, not an Intel chip)?

Yes I have M2

**Comment by ryantrem** [comment]
Ok in that case, I believe this is the same issue as #451 (the BRN package does not currently support ARM64 simulator). @SergioRZMasson - could you add your workaround steps to #451 to help provide at least a temp solution to this problem?
