### ISSUE TITLE
Can't build Babylon React Native Playground on iOS

### ISSUE THREAD

**Issue by okwasniewski** [BabylonJS/BabylonReactNative#653]
Hey,

I just wanted to make sure I did everything right, because I can't get RNTA based Test App to run on iOS. 

This is the error that I'm getting: 

![CleanShot 2024-08-28 at 13 07 54@2x](https://github.com/user-attachments/assets/026f1d17-379e-4443-8f45-3d9908d4d8a4)

Steps: 

1. cd Apps/BRNPlayground && npm install
2. cd Package && npm install
3. npx gulp buildIOSRNTA
4. In theory the https://github.com/BabylonJS/BabylonReactNative/blob/master/Apps/BRNPlayground/postinstall.js file should do all the setup but it still wasn't working :( 

Just wanted to make sure I didn't miss an important step. If not Im going to try to fix it

**Comment by okwasniewski** [comment]
It would be great if you could confirm if you are also running into this issue cc: @CedricGuillemet, @ryantrem

**Comment by CedricGuillemet** [comment]
IIRC this is linked to CMake version. try with 3.26.4 or <
Did you try to build to build the legacy Playground?

**Comment by okwasniewski** [comment]
@CedricGuillemet Unfortunately, no luck with downgrading CMake. I didn't try legacy Playground because I need RNTA to get visionOS working. I'm going to investigate it further.

**Comment by okwasniewski** [comment]
I finally got it to build with CMake 3.24.0

By looking at the changelog it appears that a default behaviour for adding library search paths has been removed which may break the example. 
 
![CleanShot 2024-08-29 at 14 11 38@2x](https://github.com/user-attachments/assets/a1b6ee97-ae21-41de-ab15-b685a0d31510)

I think we can bring back the old behaviour for newer CMake versions

**Comment by okwasniewski** [comment]
This got fixed by #654
