### ISSUE TITLE
App crashes when EngineView is included

### ISSUE THREAD

**Issue by steuraa** [BabylonJS/BabylonReactNative#90]
Hi, just started to experiment with AR and React Native and this library seemed like a good place to start.

I can't however get it to run on emulator or on mobile device. I first tried checking out this repo and starting the playground, but as soon as the app starts it crashes. I see the screen with the 'start XR' buttons for a second before it closes down. 
The same happens when I created a new React Native project and set up the same code from the playground.

The problem seems to be found in the useEngine hook as the engine created with that hook logs as: 

`{"INVALID_HANDLE": 65535, "_activeChannel": 0, "_activeRenderLoops": [], "_activeRequests": [], "_alphaEquation": 0, "_alphaMode": 1, "_alphaState": {"_alphaBlend": false, "_blendConstants": [null, null, null, null], "_blendEquationParameters": [null, null], "_blendFunctionParameters": [null, null, null, null], "_isAlphaBlendDirty": true, "_isBlendConstantsDirty": false, "_isBlendEquationParametersDirty": false, "_isBlendFunctionParametersDirty": false}, "_badDesktopOS": false, "_badOS": false, "_boundTexturesCache": {}, "_boundUniforms": {}, "_caps": {"astc": null, "blendMinMax": false, "canUseTimestampForTimerQuery": false, "colorBufferFloat": false, "depthTextureExtension": false, "drawBuffersExtension": false, "etc1": null, "etc2": null, "fragmentDepthSupported": false, "highPrecisionShaderSupported": true, "instancedArrays": false, "maxAnisotropy": 16, "maxCombinedTexturesImageUnits": 32, "maxCubemapTextureSize": 512, "maxFragmentUniformVectors": 16, "maxMSAASamples": 1, "maxRenderTextureSize": 512, "maxTextureSize": 512, "maxTexturesImageUnits": 16, "maxVaryingVectors": 16, "maxVertexAttribs": 16, "maxVertexTextureImageUnits": 16, "maxVertexUniformVectors": 16, "pvrtc": null, "standardDerivatives": true, "textureFloat": false, "textureFloatLinearFiltering": false, "textureFloatRender": false, "textureHalfFloat": false, "textureHalfFloatLinearFiltering": false, "textureHalfFloatRender": false, "textureLOD": true, "uintIndices": false, "vertexArrayObject": true}, "_colorWrite": true, "_colorWriteChanged": true, "_compiledEffects": {}, "_contextWasLost": false, "_currentBoundBuffer": [], "_currentBufferPointers": [], "_currentFramebuffer": null, "_currentInstanceBuffers": [], "_currentInstanceLocations": [], "_currentTextureChannel": -1, "_deltaTime": 0, "_depthCullingState": {"_cull": null, "_cullFace": null, "_depthFunc": null, "_depthMask": true, "_depthTest": true, "_frontFace": null, "_isCullDirty": false, "_isCullFaceDirty": false, "_isDepthFuncDirty": false, "_isDepthMaskDirty": true, "_isDepthTestDirty": true, "_isFrontFaceDirty": false, "_isZOffsetDirty": false, "_zOffset": 0}, "_deterministicLockstep": false, "_doNotHandleContextLost": false, "_drawCalls": {"_average": 0, "_current": 0, "_lastSecAccumulated": 0, "_lastSecAverage": 0, "_lastSecTime": 0, "_lastSecValueCount": 0, "_max": 0, "_min": 0, "_startMonitoringTime": 0, "_totalAccumulated": 0, "_totalValueCount": 0}, "_fps": 60, "_getDepthStencilBuffer": [Function anonymous], "_highPrecisionShadersAllowed": true, "_internalTexturesCache": [], "_lockstepMaxSteps": 4, "_maxSimultaneousTextures": 0, "_mustWipeVertexAttributes": false, "_native": {"__native__": {}}, "_nextFreeTextureSlots": [], "_performanceMonitor": {"_enabled": true, "_rollingFrameTime": {"_m2": 0, "_pos": 0, "_sampleCount": 0, "_samples": [Array], "average": 0, "variance": 0}}, "_renderingQueueLaunched": false, "_shaderProcessor": {}, "_stencilState": {"_isStencilFuncDirty": true, "_isStencilMaskDirty": true, "_isStencilOpDirty": true, "_isStencilTestDirty": true, "_stencilFunc": 519, "_stencilFuncMask": 255, "_stencilFuncRef": 1, "_stencilMask": 255, "_stencilOpDepthFail": 7680, "_stencilOpStencilDepthPass": 7681, "_stencilOpStencilFail": 7680, "_stencilTest": false}, "_texturesSupported": [], "_timeStep": 0.016666666666666666, "_uintIndicesCurrentlySet": false, "_uniformBuffers": [], "_unpackFlipYCached": null, "_vaoRecordInProgress": false, "_vertexAttribArraysEnabled": [], "_viewportCached": {"w": 0, "x": 0, "y": 0, "z": 0}, "_webGLVersion": 2, "_windowIsBackground": false, "canvasTabIndex": 1, "cullBackFaces": true, "customAnimationFrameRequester": null, "disableManifestCheck": false, "disablePerformanceMonitorInBackground": false, "disableUniformBuffers": true, "disableVertexArrayObjects": false, "enableOfflineSupport": false, "enableUnpackFlipYCached": true, "forcePOTTextures": false, "isFullscreen": false, "isPointerLock": false, "onAfterShaderCompilationObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onBeforeShaderCompilationObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onBeforeTextureInitObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onBeginFrameObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onCanvasBlurObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onCanvasFocusObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onCanvasPointerOutObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onContextLostObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onContextRestoredObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onEndFrameObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onNewSceneAddedObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "onResizeObservable": {"_eventState": {"currentTarget": undefined, "mask": 0, "skipNextObservers": false, "target": undefined}, "_observers": []}, "postProcesses": [], "premultipliedAlpha": true, "preventCacheWipeBetweenFrames": false, "renderEvenInBackground": true, "scenes": [], "useReverseDepthBuffer": false, "validateShaderPrograms": false}` 

If I initiate the EngineView component without any size style (removing the style={{flex: 1}}), the app stays stable.

@babylonjs/core: 4.1.0
@babylonjs/react-native: 0.3.0-alpha.20

**Comment by jensdev** [comment]
@steuraa I think this is related to the version of @babylonjs/core. Try it with "@babylonjs/core": "^4.2.0-beta.9"

**Comment by asteurba** [comment]
Fixed it indeed :+1: 
This can be closed

**Comment by ryantrem** [comment]
Happy to hear you are trying it out! Let us know if you have any questions!
