### ISSUE TITLE
"Hello, World"-style quick-start guide

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonReactNative#91]
Consider creating a quick-start guide for developers with little to no context to go from zero to Babylon cube as quickly as possible. This may or may not be valuable depending on the target audience, and we have most of the pieces already, but collecting all the steps into an easy-to-find, easy-to-follow minimum might be helpful for brand new developers. Some helpful things that might be contained include the following:

- Direct users to the instructions for creating a **TypeScript** React Native app. The default React Native instructions if you just look up how to create your first React Native app don't include TypeScript, which may add confusion for new developers who don't know to look for that.
- Include the direct npm commands to install the various components.
- Specifically call out the manual version setting for the Babylon.js and Babylon React Native peer dependencies. There are already warnings about this, but they appear in what looks like log spew that new and/or unwary developers might easily miss.

**Comment by alessandro-bottamedi** [comment]
Hi, i can't figure it out from the readme, are there now npm packages to install babylon directly in an esistono React-native app? something like "npm install @babylon/react-native"?

**Comment by syntheticmagus** [comment]
Hi alessandro-bottamedi,

I think the command you typed above is exactly the right one, though I'm not an expert. Generally, the documentation we have around usage is in the [package README](https://github.com/BabylonJS/BabylonReactNative/blob/master/Modules/@babylonjs/react-native/README.md). If there's something more specific you'd like to know more about, please ask a question on the [forum](https://forum.babylonjs.com/); that's the best place to get an answer quickly from the people who really know this project best. (Though please bear in mind that response times might be a good bit slower this time of year because of the holidays. 😄)

**Comment by ryantrem** [comment]
This is the package: https://www.npmjs.com/package/@babylonjs/react-native

**Comment by bghgary** [comment]
Using @SergioRZMasson's repo for this. Need to move the repo to a more official place.

**Comment by bghgary** [comment]
@SergioRZMasson and I moved the repo and did a pass on the readme. There is an issue with Android that @SergioRZMasson is investigating.

https://github.com/BabylonJS/BabylonReactNativeSample

**Comment by bghgary** [comment]
Done for now.
