### ISSUE TITLE
Default Babylon Native state on empty scene

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonReactNative#93]
If you create a scene with nothing in it, this will cause Babylon Native to issue no draw calls, and default render state will display. On Android, this results in an empty bgfx-purple backbuffer and an infinite framerate because Babylon Native's state-setting changes only take effect on a `bgfx::frame()`, which isn't happening.

**Comment by CedricGuillemet** [comment]
Fixed! Tested with 1.8.2 on Android. a touch drawcall is encoded for bgfx so now bgfx:frame does something. https://github.com/BabylonJS/BabylonNative/blob/ec4c6ea909d585161269e8f84fcf9fcbf7d6d711/Core/Graphics/Source/FrameBuffer.cpp#L97
